[package]
name = "file_combiner_gui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "file_combiner_gui"
path = "src/main.rs"

[dependencies]
eframe = "0.27"
egui = "0.27"
rfd = "0.14"
bitnet-tools = { path = "../" }
